
image: gyptis/gyptis:latest

stages:
  - test
  # - deploy

before_script:
  - conda activate base
  - pip install pytest pytest-cov

test:
  stage: test
  script:
    - make test

# pages:
#   stage: deploy
#   script:
#     - make less
#     - make doc
#     - mv doc/_build/html/ public/
#   artifacts:
#     paths:
#       - public
#   only:
#     - master
