
image: gyptis/gyptis:latest

stages:
  # - test
  - deploy

before_script:
  - source ~/.bashrc
  - pip install -e .
# 
# test:
#   stage: test
#   script:
#     - pip install pytest pytest-cov coverage
#     - make test
#     - coverage xml
#   artifacts:
#     reports:
#       cobertura: coverage.xml

pages:
  stage: deploy
  script:
    - make doc-req
    - make doc
    - mv doc/_build/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
