
image: gyptis/gyptis:latest

stages:
  - trigdoc
  - test
  - trigdocker

container:
  stage: trigdocker
  trigger: gyptis/docker
  only:
    - master
  

staging:
  stage: trigdoc
  trigger: gyptis/gyptis.gitlab.io
  only:
    - master

before_script:
  - source ~/.bashrc
  - pip install -e .

test:
  stage: test
  script:
    - pip install pytest pytest-cov coverage
    - make test
    - coverage xml
  artifacts:
    reports:
      cobertura: coverage.xml
