
image: gyptis/gyptis:latest

stages:
  - trigdoc
  - trigdocker
  - test

container:
  stage: trigdocker
  trigger: gyptis/docker
  only:
    - master
  

staging:
  stage: trigdoc
  trigger: gyptis/gyptis.gitlab.io
  only:
    - master


test:
  stage: test
  script:
    - source ~/.bashrc
    - pip install -e .
    - pip install -r dev/requirements.txt
    - make test
    - coverage xml
  artifacts:
    reports:
      cobertura: coverage.xml
  only:
    - master
