name: gyptis
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  - fenics
  - dolfin-adjoint
  - nlopt
  - meshio
  - numpy
  - scipy
  - simpy
  - matplotlib
  - pip:
    - gmsh
    - "--editable=."
    # - gyptis
