name: gyptis
channels:
  - conda-forge
dependencies:
  - python<3.10
  - pip
  - fenics
  - dolfin-adjoint
  - nlopt
  - meshio
  - numpy
  - scipy
  - simpy
  - matplotlib
  - joblib
  - psutil
  - ipython
  - loguru
  - pip:
    - gmsh
    - git+https://gitlab.com/gyptis/gyptis.git
