name: gyptis
channels:
  - conda-forge
dependencies:
  - python>3.10
  - boost==1.84.0
  - pip
  - fenics
  - dolfin-adjoint
  - meshio
  - numpy
  - scipy
  - simpy
  - matplotlib
  - pyvista
  - joblib
  - psutil
  - ipython
  - loguru
  - gmsh
  - python-gmsh
  - nlopt
  - pip:
    - git+https://gitlab.com/gyptis/gyptis.git
